### ISSUE TITLE
Ban nodes that are lower then version 9.12.1

### ISSUE THREAD

**Issue by terracoin** [diego-ab/terracoin-dev#1]
We need to ban all nodes that are lower then version 9.12.1.  Usually those are around 0.8.0.4.  Those clients are clients that haven't been updated since before the last hard fork.

**Comment by terracoin** [comment]
This is on the mainnet.

**Comment by terracoin** [comment]
Should we ban all nodes that are lower then the current version after the hard fork?

**Comment by diego-ab** [comment]
The changes I implemented will boot all legacy peers after the hardfork. I wouldn't boot the _very_ old clients right now, it is better to do this kind of thing on a set block.

**Comment by diego-ab** [comment]
Implemented in 9a45e122b
