### ISSUE TITLE
Sample in masternode config

### ISSUE THREAD

**Issue by terracoin** [diego-ab/terracoin-dev#10]
When you first run the QT or daemon (probably cli too) a masternode.conf file is generated with this sample info:

# Masternode config file
# Format: alias IP:port masternodeprivkey collateral_output_txid collateral_output_index
# Example: mn1 127.0.0.2:19999 93HaYBVUCYjEMeeH1Y4sBGLALQZE1Yc1K64xiqgX37tGBDQL8Xg 2bcd3c84c84f87eaa86e4e56834c92927a07f9e18718810b92e0d0324456a67c 0

Can the sample port be changed to 13333?  Thanks!

**Comment by terracoin** [comment]
Oh.  I see you already had an issue open for this.  I guess I forgot I put it in.  It looks like in the testnet folder this has been fixed but in the main folder it is still showing :19999.  Thanks!

**Comment by diego-ab** [comment]
This has been changed already - to test it you need to remove the file that is already there and allow it to be recreated. Files that have been created before the change won't be updated.
