### ISSUE TITLE
Mainnet always says it is out of sync

### ISSUE THREAD

**Issue by terracoin** [diego-ab/terracoin-dev#3]
I assume this will be fixed once the hard fork happens and a masternode comes online.  This does make it look like something is broken though.  I can send coins to the mainnet wallet regardless.

**Comment by diego-ab** [comment]
Ordinary nodes need to be connected to a masternode to fully sync - shouldn't be an issue on the mainnet. Will close as this is a requirement in the code and can't really be changed as masternodes are needed for most things.
