### ISSUE TITLE
Old masternodes

### ISSUE THREAD

**Issue by terracoin** [diego-ab/terracoin-dev#4]
The old masternodes that have been deleted, or shutdown do not fall off the list. 
![old masternodes](https://user-images.githubusercontent.com/24829152/30232061-b6f878da-94a2-11e7-8542-984efe5975ab.png)

**Comment by diego-ab** [comment]
Masternode will stay on the masternode list unless its output is spent. I manually verified the outputs for those masternodes and they are kosher, it looks like they got "resurrected" when you loaded up a node with an older chain and the whole network reorged.
