### ISSUE TITLE
Rewards being sent to masternodes which are down.

### ISSUE THREAD

**Issue by terracoin** [diego-ab/terracoin-dev#5]
Rewards are getting sent to masternodes that are currently down.

![image](https://user-images.githubusercontent.com/24829152/30244269-e10896f0-956f-11e7-9ee6-e148835fc3b6.png)

![image](https://user-images.githubusercontent.com/24829152/30244273-eee50d1c-956f-11e7-8bb0-fc3847bc969e.png)

**Comment by diego-ab** [comment]
I tested the issue and it doesn't look like they are being paid in error. Masternode will stay in the payment queue for up to an hour after is it switched off. If you see / suspect that it is paid in error (past the hour) here are commands that will provide useful info:

`./terracoin-cli -testnet masternodelist lastpaidblock`

`./terracoin-cli -testnet masternodelist rank`

`./terracoin-cli -testnet masternodelist activeseconds`

`./terracoin-cli -testnet masternodelist lastseen`
